version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "80:80"
      - "443:443" # HTTPS порт
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - /etc/ssl/projectsc_ai/fullchain.crt:/etc/nginx/ssl/fullchain.crt:ro
        - /etc/ssl/projectsc_ai/projectsc_ai.key:/etc/nginx/ssl/projectsc_ai.key:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9000"
