version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "80:80"
      - "443:443" # HTTPS порт
    volumes:
      - /etc/letsencrypt/live/projectsc.ai/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/projectsc.ai/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9000"
