version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    ports:
      - "443:80" # Если SSL работает через HTTPS
      # Или используйте другой порт, например:
      # - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "9000"

