version: '3.8'

services:
  vue:
    image: node:18
    working_dir: /app
    volumes:
      - ./AiPr:/app
    command: sh -c "npm install && npm run build"
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/var/www/html
      - ./AiPr/dist:/var/www/html/frontend
    ports:
      - "80:80"
    depends_on:
      - php
      - vue
